import '@/app/globals.css'

export const metadata = {
  title: 'boundToTheOath(station)',
  description: 'Generated by create next app by myla :) test edit',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body>
        {children}
      </body>
    </html>
  )
}
